theme: jekyll-theme-cayman
title: Exploring Genetic Programming Systems with MAP-Elites
description: Genetic Programming Theory and Practice XVI Contribution by Emily Dolson, Alexander Lalejini, and Charles Ofria